---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./resources/talos-cloud-controller-manager.yaml
patches:
  - path: ./patches/cilium.yaml
    target:
      kind: Kustomization
      name: cilium
