---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../_base
patches:
  - path: ./patches/flux-instance.yaml
    target:
      kind: Kustomization
      name: flux-instance
