---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
  - ../../_profiles/prod
  - ../../_variants/proxmox-vm
  - ../../_variants/talos
resources:
  - ./resources/ciliumloadbalancerippool.yaml
  - ./resources/ciliuml2announcementpolicy.yaml
patches:
  - path: ./patches/flux-instance.yaml
    target:
      kind: Kustomization
      name: flux-instance
