---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-ingress
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      service/advertise: cilium-ingress
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: node-role.kubernetes.io/etcd
        operator: DoesNotExist
  interfaces:
    - ^eth0$
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress-nginx-controller
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      service/advertise: ingress-nginx-controller
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: node-role.kubernetes.io/etcd
        operator: DoesNotExist
  interfaces:
    - ^eth0$
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: layer2
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      service/advertise: l2
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: node-role.kubernetes.io/etcd
        operator: DoesNotExist
  interfaces:
    - ^eth0$
