---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-ingress
spec:
  blocks:
    - cidr: 172.19.4.150/32
  serviceSelector:
    matchLabels:
      service/advertise: cilium-ingress
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-nginx-controller
spec:
  blocks:
    - cidr: 172.19.4.250/32
  serviceSelector:
    matchLabels:
      service/advertise: ingress-nginx-controller
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: layer2
spec:
  blocks:
    - cidr: 172.19.5.0/24
    - cidr: 172.19.6.0/24
  serviceSelector:
    matchLabels:
      service/advertise: l2
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: layer3
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 172.19.7.0/24
  serviceSelector:
    matchLabels:
      service/advertise: l3
